services:
  cryptograms:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - RUST_LOG=debug
      - QUOTES_FILE=quotes.json
      - WORDS_FILE=words.txt

  postgres:
    image: postgres:15.1-bullseye
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  db:
