services:
  cryptograms:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - RUST_LOG=debug
      - QUOTES_FILE=quotes.json
      - WORDS_FILE=words.txt
      - RUSTFLAGS=-Cinstrument-coverage
      - LLVM_PROFILE_FILE=cryptograms-%p-%m.profraw
      - CRYPTOGRAMS_PG_URL=postgres://postgres:postgres@postgres:5432
    command: ["cargo", "test", "--no-fail-fast"]

  postgres:
    image: postgres:15.1-bullseye
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
