name: Coverage

on:
  push:
    paths-ignore:
      - "tests/**"
      - "src/**"
      - ".github/workflows/**"

jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No change to coverage"'
